### ISSUE TITLE
Few tweaks in the Portfolio tab

### ISSUE THREAD

**Issue by s1-ranjan** [taoteh1221/DFD_Cryptocoin_Values#12] opened 2020-07-27 13:27 UTC
There are few tweaks that can be performed on various tabs
i. It would be good to add a blank space in the currency symbol and numeral value, as of now the default look is **$10000** it will be good if it look like **$ 10000**, this can be extended to the graph part also
ii. In the Portfolio page the first column is for short and it does not look good to show a random number in the beginning of a list, so it would be better to drop the first column  from the present interface.
iii. The names of the Asset should be aligned left as of now they are appearing to be aligned right 
iv. In the portfolio page at the bottom of the page, it shows only one single value of the Crypto asset in term of the selected exchange, it would be nice if it list all the values, in following way.
**Bitcoin is trading @ ₹ 770,809.74 on LocalBitcoins, @ ₹ 783,000.00 on Bitbns, @ ₹794,037.40 on BuyuCoin, @ ₹785,009.01 on ZebPay.**
From the above type of information the different prices in all the exchange can be viewed at once.
v. It would be nice if the above information type display the prices for all the assets that are been listed in the Asset Name, rather than the single Asset for Bitcoin.
![Screenshot_2020-07-27 DFD Cryptocoin Values - Portfolio Tracker](https://user-images.githubusercontent.com/20767253/88547095-e19c0300-d03a-11ea-9a32-2a05f7fe94e0.png)

**Comment by taoteh1221** [comment] 2020-07-28 20:36
You can already add a space next to $ or any other currencies here in config.php very easily if that's what you prefer (just add a space AFTER the symbol inside the single quotes): https://github.com/taoteh1221/DFD_Cryptocoin_Values/blob/master/config.php#L608

As for the rest of your ideas: I'm sorry but I don't agree they improve the interface, in fact they would make it more confusing in my opinion...but your welcome to fork the project and modify it to whatever you want, since it's free open source.

**Comment by s1-ranjan** [comment] 2020-07-29 14:21
Thanks for providing me that valuable information, well let me try to reexplain my ideas once again,this time visually 
i. I am talking to remove this column from the portfolio page.
![1](https://user-images.githubusercontent.com/20767253/88808145-1f7e6000-d1d0-11ea-84a7-e73976b409ff.png)
By removing this  column it'll increase the screen real-estate, moreover the list will look good with no serial number as in the above case.
ii. There is already a dual representation of values please have a look
![2](https://user-images.githubusercontent.com/20767253/88808798-f0b4b980-d1d0-11ea-8380-ac6a6d5b34c6.png)
So from the above image we find dual representation of the values, instead of showing the values twice it would be good if we have a something like this view
![Screenshot from 2020-07-27 18-02-01](https://user-images.githubusercontent.com/20767253/88811434-2ad38a80-d1d4-11ea-8c1d-1a9bae111ec7.png)
I fell this type of interface not be confusing to any body, rather than this will deliver maximum information in one go, let me know about your thoughts on this.

**Comment by taoteh1221** [comment] 2020-07-29 19:22
On i:
This is the original sort order (the order of the assets in config.php). It takes up very little screen real estate and is there to return quickly to the default sort order (by clicking on the word 'Sort' at the top of the data column).

On ii:
This is NOT a duplicate of the chosen bitcoin market, this is the chosen currency market on the settings page. Therefore it only displays the user's chosen currency market and nothing more. Also, adding additional information here is excess clutter that's very confusing to the eye. This app's primary goals are to be minimal / simple / private / easy to use and understand.

Thanks for the feedback though, I appreciate the time you took to give your feedback on these features. I still am not convinced any of these changes make the app simpler / easier to use.

**Closed** 2020-08-04 15:23 UTC
Labels: invalid
