### ISSUE TITLE
v4.8.5 is not properly working

### ISSUE THREAD

**Issue by s1-ranjan** [taoteh1221/DFD_Cryptocoin_Values#7] opened 2020-02-28 06:41 UTC
After upgrading to v4.8.5, the website broke in Firefox and it gives the following output.
![Screenshot_2020-02-28 DFD Cryptocoin Values](https://user-images.githubusercontent.com/20767253/75516792-3ce1af00-5a23-11ea-8831-2bc62cbdba7b.png)
where as in Brave browser it works with no issue but it fails to render chart.

**Comment by taoteh1221** [comment] 2020-02-28 18:49
Confirmed FF issues, thanks for the report. I tested with Brave v1.1.23, and the charts worked fine for me. What Brave version are you running?

**Comment by taoteh1221** [comment] 2020-02-28 19:11
FYI, I'm not getting the same issue you are in FF, but I am getting some issues that are rather odd (msie / chrome / brave look fine on my setup).

Could you possibly look at your /cache/logs/errors.log file, to check for any logged errors?

**Comment by taoteh1221** [comment] 2020-02-28 19:59
@s1-ranjan I only having FF issues in v73 on Ubuntu, but only with CSS styling and cookie management (I think my FF install is corrupt), could not replicate your issue. I tried FF v72.0.2 on Windows, and FF v73 on Windows, and both work fine. 

I would try 2 things if I were you:

1) Re-install v4.08.5 from this direct github link: https://github.com/taoteh1221/DFD_Cryptocoin_Values/archive/4.08.5.zip

2) Re-install Firefox if that doesn't help

We'll figure it out, let me know how it goes?

**Comment by taoteh1221** [comment] 2020-02-28 21:01
@s1-ranjan Additionally, if you have customized settings in config.php, make sure there are no mistakes in the formatting. The best way to troubleshoot that is a fresh install with default config.php settings to start...then carefully add your custom config.php settings one by one, and reload the app webpage to be sure you didn't break anything.

**Comment by taoteh1221** [comment] 2020-02-29 07:14
@s1-ranjan Are you on Firefox on a Windows or Linux machine? Been testing more, and all linux downloads for v73 have weird issues for me with CSS when visiting websites, and the portfolio app (even after clearing my ~/.mozilla settings directory). Firefox v73 on my 2 Windows machines works ok, no issues displaying the portfolio app including charts.

**Comment by s1-ranjan** [comment] 2020-02-29 07:24
@taoteh1221 I am on Ubuntu Machine with Firefox v-73.0.1 (64-bit), I feel Issue is with css

**Comment by s1-ranjan** [comment] 2020-02-29 07:26
and my brave details : Version 1.4.95 Chromium: 80.0.3987.122 (Official Build) (64-bit)

**Comment by s1-ranjan** [comment] 2020-02-29 07:33
Its very deficult to recall when I have last used Windows, may be more than 10 years back, when xp was there in the market and the virus problems, then one of my friend suggested to try with linux, after my trying  Ubuntu I saied goodbye to windows world...

**Comment by taoteh1221** [comment] 2020-02-29 18:45
I checked the CSS, there do not appear to be any issues whatsoever, and everything runs fine in MSIE / FF windows version / Chrome / Webkit / Brave v1.1.23. 

Like I said, FireFox on Windows works fine, but FireFox seems to have messed up their linux builds for latest versions. Sorry, there is nothing that can be done except switch to Chromium until Firefox fixes the poor build quality issues for linux. 

As for Brave browser, same thing. Nothing I can do as the charts display perfectly fine on Brave v1.1.23 and every other browser. Maybe their ad blocker technology is accidentally blocking the charts, because it thinks they are ads. Try enabling ads for the webpage running the app in Brave, and see if it fixes the issue.

**Comment by taoteh1221** [comment] 2020-02-29 23:11
@s1-ranjan Please test your FF linux browser here, and tell me if it looks better?
https://dragonfrugal.com/coin-prices/
The CSS here is verified completely valid (just one error I verified is a false positive) here:
https://validator.w3.org/nu/?doc=https%3A%2F%2Fdragonfrugal.com%2Fcoin-prices%2F

**Comment by s1-ranjan** [comment] 2020-03-01 01:23
@taoteh1221 I visited the above link and I found every thing is working fine on both the browser in my Linux box.

**Comment by taoteh1221** [comment] 2020-03-01 03:11
> @taoteh1221 I visited the above link and I found every thing is working fine on both the browser in my Linux box.

Great news, I will release a bug fix tomorrow for you to download. Thanks very much for the feedback @s1-ranjan :smile:

**Comment by s1-ranjan** [comment] 2020-03-01 05:07
@taoteh1221 does it'll work out of box or I'll have to reset my chase folder?

**Comment by taoteh1221** [comment] 2020-03-01 16:27
You should be able to leave the cache folder. Just be careful when you edit config.php, check you don't break the app while you edit it.

**Comment by taoteh1221** [comment] 2020-03-02 18:28
Latest release is out now @s1-ranjan : https://github.com/taoteh1221/DFD_Cryptocoin_Values/releases

Be careful when you edit config.php, as that can break the app if you create code errors. Closing this issue, just holler if you have anymore problems. Thanks very much for your feedback. :+1:

**Closed by taoteh1221** 2020-03-02 18:28 UTC
